networks:
  nw-letto:
    external: true

# Der Name bestimmt das Projekt und sollte bei jeder yml-Datei unterschiedlich sein - er kann mit -p bei docker-compose überschrieben werden
name: letto-plugin-python

services:
  pluginpython:
    image: lettohub/letto-plugin-python:latest
    restart: always
    networks:
      - nw-letto
    hostname: letto-pluginpython
    container_name: letto-pluginpython
    deploy:
      resources:
        limits:
          memory: "${PLUGIN_MEMORY_LIMIT:-500m}"
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "3"
    volumes:
      - ${VOLUME_LOG:-/opt/letto/docker/storage/log}/pluginpython:/log
      - ${VOLUME_IMAGES:-/opt/letto/docker/storage/images}:/opt/letto/images
      - ${VOLUME_PLUGINS:-/opt/letto/docker/storage/plugins}:/opt/letto/plugins
    ports:
      - "8209:8080"
      - "5209:5080"
    environment:
      TZ: ${TIMEZONE:-Europe/Berlin}
      LC_ALL: ${LOCALE:-de_DE.UTF-8}
      letto_schulen: ${LETTO_SCHULEN}
      SERVICEPATH: "/pluginpython"
      RESOURCE_DIR: "/app/resources"
      network_letto_address: letto-pluginpython
      docker_container_name: letto-pluginpython
      servername: ${SERVER_NAME}
      letto_user_user_password: ${SERVICE_USER_PASSWORD}
      letto_user_gast_password: ${SERVICE_GAST_PASSWORD}
      letto_setup_uri: ${LETTO_SETUP_URI:-http://letto-setup.nw-letto:8096}
      letto_plugin_uri_intern: ${LETTO_PLUGIN_URI_INTERN:-http://letto-pluginpython.nw-letto:8080}
      letto_plugin_uri_extern: ${LETTO_PLUGIN_URI_EXTERN:-https://${SERVER_NAME}}${SERVICEPATH}
      letto_pathImages: /opt/letto/images
      letto_pathPlugins: /opt/letto/plugins
      letto_webPathImages: ${SERVER_NAME}/images
      letto_webPathPlugins: ${SERVER_NAME}/images/plugins
      debug: ${DEBUG_PLUGINS:-${DEBUG:-false}}
      PluginPythonLogLevel: ${PLUGIN_PYTHON_LOG_LEVEL:-INFO}

  jobe:
    build:
      context: ..
      dockerfile: jobe/Dockerfile
    image: trampgeek/jobeinabox:latest
    container_name: letto-jobe
    hostname: letto-jobe
    restart: always
    ports:
      - "4000:80"
    networks:
      - nw-letto
